version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_APIKEY=${FIREBASE_APIKEY}
      - FIREBASE_AUTHDOMAIN=${FIREBASE_AUTHDOMAIN}
      - FIREBASE_DATABASEURL=${FIREBASE_DATABASEURL}
      - FIREBASE_PROJECTID=${FIREBASE_PROJECTID}
      - FIREBASE_STORAGEBUCKET=${FIREBASE_STORAGEBUCKET}
      - FIREBASE_MESSAGINGSENDERID=${FIREBASE_MESSAGINGSENDERID}
      - FIREBASE_APPID=${FIREBASE_APPID}
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT}
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 